{% set name = "svg2tikz" %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/svg2tikz-{{ version }}.tar.gz
  sha256: f430668991faae5c359cc6d2aee2be622e1825b80dcf0eed65dba2bfd6a1395a

build:
  entry_points:
    - svg2tikz = svg2tikz.tikz_export:main_cmdline
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - lxml >=5.1.1
    - inkex 1.4.0

test:
  imports:
    - svg2tikz
  commands:
    - pip check
    - svg2tikz --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/svg2tikz/
  summary: Tools for converting SVG graphics to TikZ/PGF code
  license: GPL-2.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/xyz2tex/svg2tikz
  doc_url: http://xyz2tex.github.io/svg2tikz

extra:
  recipe-maintainers:
    - anjos
